# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jPlm_BTM5RcGiDbHqNe_eXRLmj75FZEm
"""

# Python Weather Program

# Sample weather data (city, temperature in Celsius)
weather_data = {
    'New York': [5, 8, 3, 7, 9],
    'London': [4, 6, 2, 5, 7],
    'Tokyo': [10, 12, 11, 9, 13],
    'Sydney': [20, 18, 22, 19, 21]
}

# Function to calculate mean temperature for each city
def calculate_mean_temperatures(data):
    mean_temperatures = {}
    for city, temps in data.items():
        mean_temp = sum(temps) / len(temps)
        mean_temperatures[city] = mean_temp
    return mean_temperatures

# Function to calculate maximum temperature for each city
def calculate_max_temperatures(data):
    max_temperatures = {}
    for city, temps in data.items():
        max_temp = max(temps)
        max_temperatures[city] = max_temp
    return max_temperatures

# Function to calculate minimum temperature for each city
def calculate_min_temperatures(data):
    min_temperatures = {}
    for city, temps in data.items():
        min_temp = min(temps)
        min_temperatures[city] = min_temp
    return min_temperatures

# Main function
def main():
    # Calculate mean temperatures for each city
    mean_temps = calculate_mean_temperatures(weather_data)
    print("Mean Temperatures:")
    for city, temp in mean_temps.items():
        print(f"{city}: {temp}°C")

    # Calculate maximum temperatures for each city
    max_temps = calculate_max_temperatures(weather_data)
    print("\nMaximum Temperatures:")
    for city, temp in max_temps.items():
        print(f"{city}: {temp}°C")

    # Calculate minimum temperatures for each city
    min_temps = calculate_min_temperatures(weather_data)
    print("\nMinimum Temperatures:")
    for city, temp in min_temps.items():
        print(f"{city}: {temp}°C")

if __name__ == "__main__":
    main()

def calculate_mean_temperatures(data):
    mean_temperatures = {}
    for city, temps in data.items():
        mean_temp = sum(temps) / len(temps)
        mean_temperatures[city] = mean_temp
    return mean_temperatures